sudo: false
language: node_js

node_js:
  - "8"
  - "7"
  - "6"
  - "node"

install:
  - "npm install"

jobs:
  include:
    - stage: lint
      script: npm run lint
      install: skip
    - stage: test
      script: npm run test
      node_js:
        - "8"
        - "7"
        - "6"
      deploy:
            provider: npm
            email: $NPM_PUBLISH_EMAIL
            api_key: $NPM_PUBLISH_API_KEY
            on:
              tags: true
              branch: master
              node: "8"
              repo: "kontrollanten/error-shots"

cache:
  directories:
    - node_modules